project:
  type: website
  output-dir: docs
  preview:
    port: 3333
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!archive/"

website:
  title: "MUSA 550"
  page-footer:
    left: "idavis1@sas.upenn.edu"
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.iandavis1937.com/
        text: "Personal Website"
      - icon: github
        href: https://github.com/MUSA-550-Fall-2024/
        text: "MUSA 550 GitHub"
      - icon: twitter
        href: https://www.linkedin.com/in/ian-davis-b53364b1/
        text: "LinkedIn"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: about.qmd
        text: About Me
      - href: analysis.ipynb
        text: Analysis
      - href: thank_you.qmd
        text: Acknowledgements
      
format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

bibliography: references.bib
